name: Build & Deploy React (Vite) to Hostinger via FTPS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps (npm ci)
        run: npm ci

      - name: Create .env.production from example + secrets
        run: |
          if [ -f .env.example ]; then cp .env.example .env.production; fi
          # Añade aquí sustituciones VITE_* si las usas (opcional)
          # if [ -n "${{ secrets.VITE_API_URL }}" ]; then
          #   grep -q '^VITE_API_URL=' .env.production \
          #     && sed -i 's|^VITE_API_URL=.*$|VITE_API_URL=${{ secrets.VITE_API_URL }}|' .env.production \
          #     || echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env.production
          # fi

      - name: Build (Vite)
        run: npm run build

      - name: Copy .htaccess into dist
        run: |
          mkdir -p dist
          cp public/.htaccess dist/.htaccess

      - name: Inspect dist contents
        run: |
          echo "Listing dist/"
          ls -la dist || true
          echo "----"
          find dist -maxdepth 2 -type f | sed 's/^/dist: /' || true

      - name: Debug FTP connection & locate correct server-dir
        run: |
          sudo apt-get update -y >/dev/null 2>&1
          sudo apt-get install -y lftp >/dev/null 2>&1

          echo "Creating local probe file…"
          echo "PROBE from GitHub Actions: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" > PROBE_FROM_ACTIONS.txt

          echo "Opening FTP session and listing common locations…"
          lftp -u "${{ secrets.FTP_USERNAME }}","${{ secrets.FTP_PASSWORD }}" -p 21 "${{ secrets.FTP_HOST }}" -e "
            set net:max-retries 1;
            set net:timeout 20;
            set ftp:passive-mode on;
            set ftp:ssl-allow false;  # cambia a true si vas a usar FTPS

            echo '';
            echo '--- PWD at login ---';
            pwd; 
            echo '--- LS at login ---';
            ls -la;

            echo '';
            echo '--- Try / ---';
            cd / || true; pwd; ls -la || true;

            echo '';
            echo '--- Try /public_html ---';
            cd /public_html || true; pwd; ls -la || true;

            echo '';
            echo '--- Try /domains ---';
            cd /domains || true; pwd; ls -la || true;

            echo '';
            echo '--- Try your configured FTP_SERVER_DIR ---';
            cd '${{ secrets.FTP_SERVER_DIR }}' || true; pwd; ls -la || true;

            echo '';
            echo '--- Upload PROBE file into configured FTP_SERVER_DIR ---';
            cd '${{ secrets.FTP_SERVER_DIR }}' || true;
            put -O '${{ secrets.FTP_SERVER_DIR }}' PROBE_FROM_ACTIONS.txt || true;

            bye;
          "


      - name: Deploy via FTP (diagnóstico)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}          # 213.130.145.92 (sin ftp://)
          username: ${{ secrets.FTP_USERNAME }}    # u385896031
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}  # veremos variantes abajo
          log-level: verbose
          timeout: 180000

