name: Build & Deploy React (Vite) to Hostinger via FTPS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps (npm ci)
        run: npm ci

      - name: Create .env.production from example + secrets
        run: |
          if [ -f .env.example ]; then cp .env.example .env.production; fi
          # A침ade aqu칤 sustituciones VITE_* si las usas (opcional)
          # if [ -n "${{ secrets.VITE_API_URL }}" ]; then
          #   grep -q '^VITE_API_URL=' .env.production \
          #     && sed -i 's|^VITE_API_URL=.*$|VITE_API_URL=${{ secrets.VITE_API_URL }}|' .env.production \
          #     || echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env.production
          # fi

      - name: Build (Vite)
        run: npm run build

      # 游녢 OJO: este bloque debe ir exactamente bajo `run: |` (con 8 espacios de indentaci칩n)
      - name: Add SPA .htaccess into dist
        shell: bash
        run: |
          mkdir -p dist
          cat > dist/.htaccess <<'HTACCESS'
# --- React + Vite SPA on Apache (Hostinger) ---
RewriteEngine On
RewriteBase /
# SPA fallback: si no es archivo/dir real, sirve index.html
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]

# Compresi칩n (si est치 disponible)
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css application/javascript application/json image/svg+xml
</IfModule>

# Cache de est치ticos
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType text/css "access plus 7 days"
  ExpiresByType application/javascript "access plus 7 days"
  ExpiresByType image/svg+xml "access plus 30 days"
  ExpiresByType image/jpeg "access plus 30 days"
  ExpiresByType image/png "access plus 30 days"
  ExpiresByType image/webp "access plus 30 days"
</IfModule>
HTACCESS

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          dangerous-clean-slate: true
