      - name: Inspect dist contents
        run: |
          echo "Listing dist/"
          ls -la dist || true
          echo "----"
          find dist -maxdepth 2 -type f | sed 's/^/dist: /' || true

      - name: Create probe file (before deploy)
        run: |
          echo "Archivo de prueba desde GitHub Actions $(date -u)" > dist/PROBE_FROM_ACTIONS.txt

      - name: Debug secrets & connectivity (no apt-get)
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_SERVER_DIR: ${{ secrets.FTP_SERVER_DIR }}
        shell: bash
        run: |
          set -e

          echo "== Secrets presentes (sin mostrar valores) =="
          [ -n "${FTP_HOST}" ] && echo "FTP_HOST: OK" || (echo "FALTA FTP_HOST" && exit 1)
          [ -n "${FTP_USERNAME}" ] && echo "FTP_USERNAME: OK" || (echo "FALTA FTP_USERNAME" && exit 1)
          [ -n "${FTP_PASSWORD}" ] && echo "FTP_PASSWORD: OK" || (echo "FALTA FTP_PASSWORD" && exit 1)
          [ -n "${FTP_SERVER_DIR}" ] && echo "FTP_SERVER_DIR: OK" || (echo "FALTA FTP_SERVER_DIR" && exit 1)

          echo
          echo "== Validaciones de formato =="
          case "${FTP_HOST}" in
            *"ftp://"*) echo "ERROR: FTP_HOST contiene 'ftp://'. QUÍTALO."; exit 1 ;;
          esac

          # Quita espacios y compara longitudes
          trimmed="$(printf '%s' "$FTP_HOST" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
          if [ "${#trimmed}" -ne "${#FTP_HOST}" ]; then
            echo "ADVERTENCIA: FTP_HOST tiene espacios al inicio/fin. Corrígelo en el secret."
          fi

          if echo "$FTP_HOST" | grep -Eq '^[0-9]{1,3}(\.[0-9]{1,3}){3}$'; then
            echo "FTP_HOST parece ser una IP (correcto)."
          else
            echo "FTP_HOST parece ser un hostname."
          fi

          echo
          echo "== Comprobando conexión TCP al puerto 21 =="
          (exec 3<>/dev/tcp/${FTP_HOST}/21 && echo "Conexión TCP a 21: OK" && exec 3>&- 3<&-) || (echo "No se pudo abrir conexión TCP a 21"; exit 1)

          echo
          echo "== Comprobación de server-dir (longitud) =="
          echo "Longitud de FTP_SERVER_DIR: ${#FTP_SERVER_DIR}"

      - name: Deploy via FTP (verbose)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}           # 213.130.145.92 (SIN 'ftp://')
          username: ${{ secrets.FTP_USERNAME }}     # u385896031
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp                            # cambia a ftps si tu server lo soporta
          port: 21
          local-dir: dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR }} # p.ej. /public_html/
          log-level: verbose
          timeout: 180000
          # dangerous-clean-slate: true             # actívalo cuando confirmes la ruta correcta
