name: Build & Deploy React (Vite) to Hostinger via FTPS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps (npm ci)
        run: npm ci

      - name: Create .env.production from example + secrets
        run: |
          if [ -f .env.example ]; then cp .env.example .env.production; fi
          # Añade aquí sustituciones VITE_* si las usas (opcional)
          # if [ -n "${{ secrets.VITE_API_URL }}" ]; then
          #   grep -q '^VITE_API_URL=' .env.production \
          #     && sed -i 's|^VITE_API_URL=.*$|VITE_API_URL=${{ secrets.VITE_API_URL }}|' .env.production \
          #     || echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env.production
          # fi

      - name: Build (Vite)
        run: npm run build

      - name: Copy .htaccess into dist
        run: |
          mkdir -p dist
          cp public/.htaccess dist/.htaccess

      - name: Inspect dist contents
        run: |
          echo "Listing dist/"
          ls -la dist || true
          echo "----"
          find dist -maxdepth 2 -type f | sed 's/^/dist: /' || true

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          dangerous-clean-slate: true
