name: Build & Deploy React (Vite) to Hostinger via FTPS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps (npm ci)
        run: npm ci

      - name: Create .env.production from example + secrets
        run: |
          if [ -f .env.example ]; then cp .env.example .env.production; fi
          # Añade aquí sustituciones VITE_* si las usas (opcional)
          # if [ -n "${{ secrets.VITE_API_URL }}" ]; then
          #   grep -q '^VITE_API_URL=' .env.production \
          #     && sed -i 's|^VITE_API_URL=.*$|VITE_API_URL=${{ secrets.VITE_API_URL }}|' .env.production \
          #     || echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env.production
          # fi

      - name: Build (Vite)
        run: npm run build

      - name: Copy .htaccess into dist
        run: |
          mkdir -p dist
          cp public/.htaccess dist/.htaccess

      - name: Deploy via FTP (verbose)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}           # 213.130.145.92 (SIN 'ftp://')
          username: ${{ secrets.FTP_USERNAME }}     # u385896031
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp                            # cambia a ftps si tu server lo soporta
          port: 21
          local-dir: dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR }} # p.ej. /public_html/
          log-level: verbose
          timeout: 180000
          # dangerous-clean-slate: true             # actívalo cuando confirmes la ruta correcta



